<?php

return [
    'HTML',
    'CSS',
    'JavaScript',
    'PHP',
    'Python',
    'Ruby',
    'Java',
    'C#',
    'C++',
    'Swift',
    'Kotlin',
    'Objective-C',
    'TypeScript',
    'Go (Golang)',
    'Rust',
    'Dart',
    'SQL',
    'NoSQL',
    'MongoDB',
    'MySQL',
    'PostgreSQL',
    'SQLite',
    'Oracle DB',
    'Redis',
    'Elasticsearch',
    'GraphQL',
    'Firebase',
    'Amazon Web Services (AWS)',
    'Microsoft Azure',
    'Google Cloud Platform (GCP)',
    'Docker',
    'Kubernetes',
    'Jenkins',
    'Git',
    'SVN (Subversion)',
    'GitLab',
    'Bitbucket',
    'Terraform',
    'Ansible',
    'Chef',
    'Puppet',
    'CloudFormation',
    'React',
    'Vue.js',
    'Angular',
    'Ember.js',
    'Svelte',
    'Tailwind CSS',
    'Bootstrap',
    'Foundation',
    'SASS/SCSS',
    'LESS',
    'Figma',
    'Sketch',
    'Adobe XD',
    'InVision',
    'Axure RP',
    'UI/UX Design',
    'Interaction Design',
    'Responsive Web Design',
    'Mobile-first Design',
    'Wireframing',
    'Prototyping',
    'Web Performance Optimization',
    'Web Accessibility (WCAG)',
    'Node.js',
    'Express.js',
    'Laravel (PHP)',
    'Django (Python)',
    'Flask (Python)',
    'Ruby on Rails',
    'ASP.NET',
    'Spring Framework (Java)',
    'Hibernate',
    'Struts',
    'Grails',
    'Elixir',
    'Symfony (PHP)',
    'FastAPI (Python)',
    'RESTful API Design',
    'GraphQL API',
    'Microservices Architecture',
    'Event-Driven Architecture',
    'WebSocket',
    'RabbitMQ',
    'Apache Kafka',
    'Message Queues',
    'Web Scraping',
    'Ethical Hacking',
    'Penetration Testing',
    'OWASP',
    'Vulnerability Assessment',
    'Network Security',
    'Firewall Configuration',
    'Malware Analysis',
    'Security Auditing',
    'Encryption Algorithms (AES, RSA)',
    'SIEM (Security Information and Event Management)',
    'Incident Response',
    'Social Engineering',
    'Cryptography',
    'Blockchain Security',
    'Zero Trust Architecture',
    'Intrusion Detection Systems (IDS)',
    'Intrusion Prevention Systems (IPS)',
    'Threat Intelligence',
    'Cloud Security (AWS, Azure, GCP Security)',
    'Data Science',
    'Machine Learning',
    'Deep Learning',
    'Natural Language Processing (NLP)',
    'Computer Vision',
    'Data Analysis (Excel, SQL)',
    'Big Data (Hadoop, Spark)',
    'Data Mining',
    'Statistical Analysis',
    'AI & ML Algorithms',
    'Time Series Forecasting',
    'Data Visualization (Tableau, Power BI)',
    'Business Intelligence (BI)',
    'TensorFlow',
    'Keras',
    'PyTorch',
    'R Programming',
    'Matlab',
    'SQL Server',
    'Data Warehousing',
    'Data Engineering',
    'Apache Hadoop',
    'Apache Spark',
    'ETL (Extract, Transform, Load)',
    'DevOps',
    'CI/CD (Continuous Integration/Continuous Deployment)',
    'Terraform',
    'Jenkins',
    'GitLab CI/CD',
    'Docker',
    'Kubernetes',
    'AWS Lambda',
    'Google Cloud Functions',
    'Azure Functions',
    'VMware',
    'Linux Administration',
    'Windows Server Administration',
    'Bash Scripting',
    'PowerShell',
    'Automation Scripts',
    'Virtualization',
    'Nginx',
    'Apache HTTP Server',
    'Load Balancing',
    'Serverless Computing',
    'Web Hosting (Apache, Nginx, IIS)',
    'Android Development',
    'iOS Development',
    'Flutter',
    'React Native',
    'Xamarin',
    'App Store Optimization (ASO)',
    'Firebase Cloud Messaging (FCM)',
    'Android Jetpack',
    'Core Data (iOS)',
    'Agile Methodology',
    'Scrum',
    'Kanban',
    'Jira',
    'Project Management (PMBOK)',
    'Risk Management',
    'Waterfall Model',
    'DevOps',
    'ITIL (Information Technology Infrastructure Library)',
    'Business Analysis',
    'Cost Estimation',
    'Stakeholder Management',
    'Product Management',
    'Cloud Computing',
    'Cloud Architecture',
    'Cloud Security',
    'Cloud Cost Optimization',
    'Serverless Architecture',
    'Cloud Native Applications',
    'Containerization (Docker, Kubernetes)',
    'Blockchain',
    'Cryptocurrency',
    'Bitcoin',
    'Ethereum',
    'NFT (Non-Fungible Tokens)',
    'Augmented Reality (AR)',
    'Virtual Reality (VR)',
    '5G Technology',
    'IoT (Internet of Things)',
    'Edge Computing',
    'Quantum Computing',
    'Search Engine Optimization (SEO)',
    'Search Engine Marketing (SEM)',
    'Content Marketing',
    'Email Marketing',
    'Social Media Marketing',
    'Influencer Marketing',
    'PPC (Pay Per Click)',
    'Google Analytics',
    'Google Ads',
    'Facebook Ads',
    'Instagram Marketing',
    'Affiliate Marketing',
    'UI Design',
    'UX Design',
    'Graphic Design',
    'Web Design',
    'Mobile UI/UX',
    'Prototyping (Figma, Adobe XD)',
    'Wireframing',
    'Design Thinking',
    '3D Design',
    'Animation and Motion Graphics',
    'Branding',
];
